stages:
- name: Compile jar
  steps:
  - runScriptConfig:
      image: maven:3-jdk-8
      shellScript: mvn clean package
- name: Create and push image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: fozat/hello_world
      pushRemote: true
      registry: index.docker.io
timeout: 60
